# Generated by Django 5.2.4 on 2025-07-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='time_in_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='timeoutrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='time_out_images/%Y/%m/%d/'),
        ),
    ]
