# Generated by Django 5.2.5 on 2025-08-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundy', '0002_alter_timeinrecord_image_alter_timeoutrecord_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='reference',
            field=models.ImageField(blank=True, null=True, upload_to='reference/%Y/%m/%d/'),
        ),
    ]
