# Generated by Django 5.2.5 on 2025-08-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundy', '0003_person_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='reference',
            new_name='image',
        ),
    ]
