# Generated by Django 5.2.5 on 2025-08-08 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundy', '0004_rename_reference_person_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('IN', 'Clock In'), ('OUT', 'Clock Out')], max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='time_images/%Y/%m/%d/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bundy.person')),
            ],
        ),
    ]
